PROC=..\tools\Transform\Transform.exe

html/thesis.html: $(SOURCES)
	cp *.png html
	$(PROC) -xsl $(HTMLXSLT) -xml thesis.xml -out $@  
	
fo/%.fo: $(SOURCES)
	$(PROC) -xsl $(FOXSLT) -xml $< -pdf $@  

pdf/thesis.pdf: $(SOURCES)
	$(FOP) -xsl $(FOXSLT) -xml thesis.xml -pdf $@  

ps/%.ps: $(SOURCES)
	$(PROC) -xsl $(FOXSLT) -xml $< -out $@   