PROC=xsltproc

html/%.html: $(SOURCES) $(MAKEFILES)
	cp $(IMAGES) html
	cp $(CSS) html
	$(PROC) --output $@ $(HTMLXSLT) $< 
	
chunked-html/index.html: $(SOURCES) $(MAKEFILES)
	cp $(IMAGES) chunked-html
	cp $(CSS) chunked-html
	$(PROC) --output $@ $(CHUNKEDHTMLXSLT) $< 
	
	
%.fo: $(SOURCES) $(MAKEFILES)
	$(PROC) $(PARAMS) $(FOPARAMS) -output $@ $(FOXSLT) $< 

pdf/thesis.pdf: thesis.fo 
	$(FOP) -fo $< -pdf $@

ps/%.ps: $(SOURCES)
	$(PROC) --docbook --output $@ $(FOXSLT) $< 

